apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-predict
spec:
  destination:
    name: ''
    namespace: stock-predict
    server: 'https://kubernetes.default.svc'
  source:
    path: object-detect-yaml
    repoURL: 'https://github.com/solution-pattern-big-data/deployment.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

