apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: stock-predict-model
    serving.kserve.io/deploymentMode: ModelMesh
    argocd.argoproj.io/sync-wave: "2"
  labels:
    name: stock-predict-model
    opendatahub.io/dashboard: "true"
  name: stock-predict-model
  namespace: stock-predict
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: "1"
      runtime: stock-predict-model-server
      storage:
        key: minio-connection
        path: stockpredict/future_trend.onnx
